import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/Footer/Footer";
import "./globals.css";
import Navbar from './components/Navbar/index';

export const metadata = {
  title: "swahili delicacies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
